//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoFetcher.MyEngine {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyEngine.ICalculationEngine")]
    public interface ICalculationEngine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationEngine/Averager", ReplyAction="http://tempuri.org/ICalculationEngine/AveragerResponse")]
        double Averager(double[] MyTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationEngine/Averager", ReplyAction="http://tempuri.org/ICalculationEngine/AveragerResponse")]
        System.Threading.Tasks.Task<double> AveragerAsync(double[] MyTable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculationEngineChannel : MongoFetcher.MyEngine.ICalculationEngine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationEngineClient : System.ServiceModel.ClientBase<MongoFetcher.MyEngine.ICalculationEngine>, MongoFetcher.MyEngine.ICalculationEngine {
        
        public CalculationEngineClient() {
        }
        
        public CalculationEngineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationEngineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationEngineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationEngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Averager(double[] MyTable) {
            return base.Channel.Averager(MyTable);
        }
        
        public System.Threading.Tasks.Task<double> AveragerAsync(double[] MyTable) {
            return base.Channel.AveragerAsync(MyTable);
        }
    }
}
